### ISSUE TITLE
continue backup operations in case of source failure

### ISSUE THREAD

**Issue by bganne** [knoxite/knoxite#54]
I have some files in my homedir which are not readable by my user (leftovers from some build process under a different user). When knoxite encounters those files it just stops. It would be great if operations could pursue anyway (logging the error).
I think this should be the default behaviour with a 'stop on error' option.

**Comment by muesli** [comment]
I think it's actually important that the default behavior is aborting the operation: never should you be under the impression that all your data has been stored in a backup, only to later discover you didn't actually backup everything because of an unexpected file permission problem.

An alternative could be continuing the backup operation, but exiting with an error eventually and printing out a list of files that couldn't be accessed.

Adding a parameter to ignore such errors is definitely planned, though.

**Comment by bganne** [comment]
Yes I was thinking about the 2nd solution, and I would be perfectly fine with an option. Should I give it a try? It could be an easy way for me to play around with go (new to me)
